services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  chuck-facts:
    image: ghcr.io/univ-smb-m1-isc-2025/chuck-facts:master
    container_name: chuck-facts
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - LOGGING_CONFIG=/data/logback_config/logback.xml
    volumes:
      - ./logback.xml:/data/logback_config/logback.xml